args: {'bs': 160, 'lr': 0.0001, 'device': 'cuda:2', 'epochs': 15, 'random_mask': True, 'prob_of_random_mask': 0.4, 'clip_project_length': 10, 'continuous_prompt_length': 10, 'max_num_of_entities': 10, 'prompt_template_length': 5, 'num_layers': 8, 'noise_variance': 0.016, 'clip_model': 'ViT-B/32', 'using_clip_features': True, 'is_rn': False, 'language_model': 'gpt2', 'using_hard_prompt': True, 'soft_prompt_first': True, 'only_hard_prompt': False, 'debug': False, 'few_shot_ratio': 1.0, 'save_every': 1, 'prefix': 'coco_prefix', 'path_of_datasets': '/data/twkim/viecap/ann/coco/coco_texts_features_ViT-B32.pickle', 'out_dir': '/data/twkim/viecap/checkpoints/train_coco', 'normalize_prefix': True, 'name_of_objects_vocabs': 'visual_genome_entities', 'path_of_objects_vocabs': '/data/twkim/viecap/ann/vocabulary/all_objects_attributes_relationships.pickle', 'frozen_gpt': False, 'num_workers': 0, 'use_amp': True, 'disable_random_seed': False, 'random_seed': 30}
Dataset Loading: /data/twkim/viecap/ann/coco/coco_texts_features_ViT-B32.pickle successful. Max sentence length: 39
Traceback (most recent call last):
  File "/home/twkim/project/viecap/main.py", line 170, in <module>
    main()
  File "/home/twkim/project/viecap/main.py", line 167, in main
    train(args, datasets, model, output_dir = args.out_dir, output_prefix = args.prefix)
  File "/home/twkim/project/viecap/main.py", line 46, in train
    model = model.to(device)
  File "/home/twkim/anaconda3/envs/viecap/lib/python3.9/site-packages/torch/nn/modules/module.py", line 989, in to
    return self._apply(convert)
  File "/home/twkim/anaconda3/envs/viecap/lib/python3.9/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/twkim/anaconda3/envs/viecap/lib/python3.9/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/twkim/anaconda3/envs/viecap/lib/python3.9/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/home/twkim/anaconda3/envs/viecap/lib/python3.9/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/home/twkim/anaconda3/envs/viecap/lib/python3.9/site-packages/torch/nn/modules/module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
